version: 0.2

phases:
  install:
    build:
      commands:
        # Initialize Terraform
        - cd ..
        - terraform init

        # Apply Terraform configuration
        - terraform apply -auto-approve
